//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wicresoft.WFH.Data
{
    using System;
    using System.Data.Linq.Mapping;
    using System.Xml.Serialization;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [Serializable]
    [DataContract]
    [XmlRoot("AccessEvent")]
    public partial class AccessEvent : BaseEntity
    {
    
        [Column(Name = "Id", DbType = "Int32", IsPrimaryKey = true, CanBeNull = false, IsDbGenerated = true)]
        public override int Id { get; set; }
    
        [Column(Name = "IpAddress", DbType = "String", CanBeNull = false)]
        public  string IpAddress { get; set; }
    
        [Column(Name = "Path", DbType = "String")]
        public  string Path { get; set; }
    
        [Column(Name = "UserId", DbType = "Int32")]
        public  Nullable<int> UserId { get; set; }
    
        [Column(Name = "YYYYMMDD", DbType = "String", CanBeNull = false)]
        public  string YYYYMMDD { get; set; }
    
        [Column(Name = "Year", DbType = "Int32", CanBeNull = false)]
        public  int Year { get; set; }
    
        [Column(Name = "Month", DbType = "Int32", CanBeNull = false)]
        public  int Month { get; set; }
    
        [Column(Name = "Days", DbType = "Int32", CanBeNull = false)]
        public  int Days { get; set; }
    
        [Column(Name = "CreatedDateTime", DbType = "DateTime", CanBeNull = false)]
    	private System.DateTime _createdDateTime;
    	public virtual System.DateTime CreatedDateTime 
    	{
    		get { return _createdDateTime; }
    		set 
    		{
    			if (value.Kind == DateTimeKind.Unspecified) {
    				_createdDateTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_createdDateTime = value;
    			}
    		}
    	}
    
        [Column(Name = "Comment", DbType = "String")]
        public  string Comment { get; set; }
        [XmlIgnore]
        public virtual  User User { get; set; }
    }
}
