//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wicresoft.WFH.Data
{
    using System;
    using System.Data.Linq.Mapping;
    using System.Xml.Serialization;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [Serializable]
    [DataContract]
    [XmlRoot("Device")]
    public partial class Device : BaseEntity
    {
    
        [Column(Name = "Id", DbType = "Int32", IsPrimaryKey = true, CanBeNull = false, IsDbGenerated = true)]
        public override int Id { get; set; }
    
        [Column(Name = "Name", DbType = "String", CanBeNull = false)]
        public  string Name { get; set; }
    
        [Column(Name = "Type", DbType = "String", CanBeNull = false)]
        public  string Type { get; set; }
    
        [Column(Name = "Description", DbType = "String")]
        public  string Description { get; set; }
    
        [Column(Name = "CeatedDateTime", DbType = "DateTime", CanBeNull = false)]
    	private System.DateTime _ceatedDateTime;
    	public virtual System.DateTime CeatedDateTime 
    	{
    		get { return _ceatedDateTime; }
    		set 
    		{
    			if (value.Kind == DateTimeKind.Unspecified) {
    				_ceatedDateTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_ceatedDateTime = value;
    			}
    		}
    	}
    
        [Column(Name = "CreateUserId", DbType = "Int32", CanBeNull = false)]
        public  int CreateUserId { get; set; }
    
        [Column(Name = "LastUpdatedDateTime", DbType = "DateTime", CanBeNull = false)]
    	private System.DateTime _lastUpdatedDateTime;
    	public virtual System.DateTime LastUpdatedDateTime 
    	{
    		get { return _lastUpdatedDateTime; }
    		set 
    		{
    			if (value.Kind == DateTimeKind.Unspecified) {
    				_lastUpdatedDateTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_lastUpdatedDateTime = value;
    			}
    		}
    	}
    
        [Column(Name = "LastUpdatedUerId", DbType = "Int32", CanBeNull = false)]
        public  int LastUpdatedUerId { get; set; }
    
        [Column(Name = "IsActive", DbType = "Boolean", CanBeNull = false)]
        public override bool IsActive { get; set; }
        [XmlIgnore]
        public virtual  User User { get; set; }
        [XmlIgnore]
        public virtual  User User1 { get; set; }
    }
}
