//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wicresoft.WFH.Data
{
    using System;
    using System.Data.Linq.Mapping;
    using System.Xml.Serialization;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [Serializable]
    [DataContract]
    [XmlRoot("Menu")]
    public partial class Menu : BaseEntity
    {
        public Menu()
        {
        }
    
    
        [Column(Name = "Id", DbType = "Int32", IsPrimaryKey = true, CanBeNull = false, IsDbGenerated = true)]
        public override int Id { get; set; }
    
        [Column(Name = "ParentId", DbType = "Int32")]
        public  Nullable<int> ParentId { get; set; }
    
        [Column(Name = "ModuleId", DbType = "Int32")]
        public  Nullable<int> ModuleId { get; set; }
    
        [Column(Name = "Order", DbType = "Int16", CanBeNull = false)]
        public  short Order { get; set; }
    
        [Column(Name = "Key", DbType = "String", CanBeNull = false)]
        public  string Key { get; set; }
    
        [Column(Name = "Name", DbType = "String", CanBeNull = false)]
        public  string Name { get; set; }
    
        [Column(Name = "Icon", DbType = "String")]
        public  string Icon { get; set; }
    
        [Column(Name = "Path", DbType = "String", CanBeNull = false)]
        public  string Path { get; set; }
    
        [Column(Name = "IsEnable", DbType = "Boolean", CanBeNull = false)]
        public  bool IsEnable { get; set; }
    
        [Column(Name = "IsActive", DbType = "Boolean", CanBeNull = false)]
        public override bool IsActive { get; set; }
        [XmlIgnore]
        public virtual  Module Module { get; set; }
        [XmlIgnore]
        private ICollection<Menu> _Menu1;
        [XmlIgnore]
        public virtual ICollection<Menu> Menu1
        {
            get { return this._Menu1 ?? (this._Menu1 = new HashSet<Menu>()); }
            set { this._Menu1 = value; }
        }
        [XmlIgnore]
        public virtual  Menu Menu2 { get; set; }
        [XmlIgnore]
        private ICollection<Permission> _Permissions;
        [XmlIgnore]
        public virtual ICollection<Permission> Permissions
        {
            get { return this._Permissions ?? (this._Permissions = new HashSet<Permission>()); }
            set { this._Permissions = value; }
        }
        [XmlIgnore]
        private ICollection<RoleMenuMap> _RoleMenuMaps;
        [XmlIgnore]
        public virtual ICollection<RoleMenuMap> RoleMenuMaps
        {
            get { return this._RoleMenuMaps ?? (this._RoleMenuMaps = new HashSet<RoleMenuMap>()); }
            set { this._RoleMenuMaps = value; }
        }
    }
}
