//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wicresoft.WFH.Data
{
    using System;
    using System.Data.Linq.Mapping;
    using System.Xml.Serialization;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [Serializable]
    [DataContract]
    [XmlRoot("Module")]
    public partial class Module : BaseEntity
    {
        public Module()
        {
        }
    
    
        [Column(Name = "Id", DbType = "Int32", IsPrimaryKey = true, CanBeNull = false, IsDbGenerated = true)]
        public override int Id { get; set; }
    
        [Column(Name = "Order", DbType = "Int16", CanBeNull = false)]
        public  short Order { get; set; }
    
        [Column(Name = "Key", DbType = "String", CanBeNull = false)]
        public  string Key { get; set; }
    
        [Column(Name = "Name", DbType = "String", CanBeNull = false)]
        public  string Name { get; set; }
    
        [Column(Name = "DisplayName", DbType = "String", CanBeNull = false)]
        public  string DisplayName { get; set; }
    
        [Column(Name = "Description", DbType = "String")]
        public  string Description { get; set; }
    
        [Column(Name = "IsActive", DbType = "Boolean", CanBeNull = false)]
        public override bool IsActive { get; set; }
        [XmlIgnore]
        private ICollection<Menu> _Menus;
        [XmlIgnore]
        public virtual ICollection<Menu> Menus
        {
            get { return this._Menus ?? (this._Menus = new HashSet<Menu>()); }
            set { this._Menus = value; }
        }
    }
}
