//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wicresoft.WFH.Data
{
    using System;
    using System.Data.Linq.Mapping;
    using System.Xml.Serialization;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [Serializable]
    [DataContract]
    [XmlRoot("Organization")]
    public partial class Organization : BaseEntity
    {
        public Organization()
        {
        }
    
    
        [Column(Name = "Id", DbType = "Int32", IsPrimaryKey = true, CanBeNull = false, IsDbGenerated = true)]
        public override int Id { get; set; }
    
        [Column(Name = "ParentId", DbType = "Int32")]
        public  Nullable<int> ParentId { get; set; }
    
        [Column(Name = "Name", DbType = "String", CanBeNull = false)]
        public  string Name { get; set; }
    
        [Column(Name = "Description", DbType = "String")]
        public  string Description { get; set; }
    
        [Column(Name = "CreatedUserId", DbType = "Int32", CanBeNull = false)]
        public  int CreatedUserId { get; set; }
    
        [Column(Name = "CreatedDateTime", DbType = "DateTime", CanBeNull = false)]
    	private System.DateTime _createdDateTime;
    	public virtual System.DateTime CreatedDateTime 
    	{
    		get { return _createdDateTime; }
    		set 
    		{
    			if (value.Kind == DateTimeKind.Unspecified) {
    				_createdDateTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_createdDateTime = value;
    			}
    		}
    	}
    
        [Column(Name = "LastUpdatedUserId", DbType = "Int32", CanBeNull = false)]
        public  int LastUpdatedUserId { get; set; }
    
        [Column(Name = "LastUpdatedDateTime", DbType = "DateTime", CanBeNull = false)]
    	private System.DateTime _lastUpdatedDateTime;
    	public virtual System.DateTime LastUpdatedDateTime 
    	{
    		get { return _lastUpdatedDateTime; }
    		set 
    		{
    			if (value.Kind == DateTimeKind.Unspecified) {
    				_lastUpdatedDateTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_lastUpdatedDateTime = value;
    			}
    		}
    	}
    
        [Column(Name = "IsActive", DbType = "Boolean", CanBeNull = false)]
        public override bool IsActive { get; set; }
        [XmlIgnore]
        public virtual  User User { get; set; }
        [XmlIgnore]
        public virtual  User User1 { get; set; }
        [XmlIgnore]
        private ICollection<Organization> _Organization1;
        [XmlIgnore]
        public virtual ICollection<Organization> Organization1
        {
            get { return this._Organization1 ?? (this._Organization1 = new HashSet<Organization>()); }
            set { this._Organization1 = value; }
        }
        [XmlIgnore]
        public virtual  Organization Organization2 { get; set; }
        [XmlIgnore]
        private ICollection<User> _Users;
        [XmlIgnore]
        public virtual ICollection<User> Users
        {
            get { return this._Users ?? (this._Users = new HashSet<User>()); }
            set { this._Users = value; }
        }
    }
}
