//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wicresoft.WFH.Data
{
    using System;
    using System.Data.Linq.Mapping;
    using System.Xml.Serialization;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [Serializable]
    [DataContract]
    [XmlRoot("Permission")]
    public partial class Permission : BaseEntity
    {
        public Permission()
        {
        }
    
    
        [Column(Name = "Id", DbType = "Int32", IsPrimaryKey = true, CanBeNull = false, IsDbGenerated = true)]
        public override int Id { get; set; }
    
        [Column(Name = "MenuId", DbType = "Int32")]
        public  Nullable<int> MenuId { get; set; }
    
        [Column(Name = "ActionId", DbType = "Int16", CanBeNull = false)]
        public  short ActionId { get; set; }
    
        [Column(Name = "Name", DbType = "String", CanBeNull = false)]
        public  string Name { get; set; }
    
        [Column(Name = "DisplayName", DbType = "String", CanBeNull = false)]
        public  string DisplayName { get; set; }
    
        [Column(Name = "Description", DbType = "String")]
        public  string Description { get; set; }
    
        [Column(Name = "IsActive", DbType = "Boolean", CanBeNull = false)]
        public override bool IsActive { get; set; }
        [XmlIgnore]
        public virtual  Menu Menu { get; set; }
        [XmlIgnore]
        private ICollection<RolePermissionMap> _RolePermissionMaps;
        [XmlIgnore]
        public virtual ICollection<RolePermissionMap> RolePermissionMaps
        {
            get { return this._RolePermissionMaps ?? (this._RolePermissionMaps = new HashSet<RolePermissionMap>()); }
            set { this._RolePermissionMaps = value; }
        }
        [XmlIgnore]
        private ICollection<UserPermissionMap> _UserPermissionMaps;
        [XmlIgnore]
        public virtual ICollection<UserPermissionMap> UserPermissionMaps
        {
            get { return this._UserPermissionMaps ?? (this._UserPermissionMaps = new HashSet<UserPermissionMap>()); }
            set { this._UserPermissionMaps = value; }
        }
    }
}
