//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wicresoft.WFH.Data
{
    using System;
    using System.Data.Linq.Mapping;
    using System.Xml.Serialization;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [Serializable]
    [DataContract]
    [XmlRoot("Role")]
    public partial class Role : BaseEntity
    {
        public Role()
        {
        }
    
    
        [Column(Name = "Id", DbType = "Int32", IsPrimaryKey = true, CanBeNull = false, IsDbGenerated = true)]
        public override int Id { get; set; }
    
        [Column(Name = "Name", DbType = "String", CanBeNull = false)]
        public  string Name { get; set; }
    
        [Column(Name = "DisplayName", DbType = "String", CanBeNull = false)]
        public  string DisplayName { get; set; }
    
        [Column(Name = "Description", DbType = "String")]
        public  string Description { get; set; }
    
        [Column(Name = "CreatedUserId", DbType = "Int32", CanBeNull = false)]
        public  int CreatedUserId { get; set; }
    
        [Column(Name = "CreatedDateTime", DbType = "DateTime", CanBeNull = false)]
    	private System.DateTime _createdDateTime;
    	public virtual System.DateTime CreatedDateTime 
    	{
    		get { return _createdDateTime; }
    		set 
    		{
    			if (value.Kind == DateTimeKind.Unspecified) {
    				_createdDateTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_createdDateTime = value;
    			}
    		}
    	}
    
        [Column(Name = "LastUpdatedUserId", DbType = "Int32", CanBeNull = false)]
        public  int LastUpdatedUserId { get; set; }
    
        [Column(Name = "LastUpdatedDateTime", DbType = "DateTime", CanBeNull = false)]
    	private System.DateTime _lastUpdatedDateTime;
    	public virtual System.DateTime LastUpdatedDateTime 
    	{
    		get { return _lastUpdatedDateTime; }
    		set 
    		{
    			if (value.Kind == DateTimeKind.Unspecified) {
    				_lastUpdatedDateTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_lastUpdatedDateTime = value;
    			}
    		}
    	}
    
        [Column(Name = "IsActive", DbType = "Boolean", CanBeNull = false)]
        public override bool IsActive { get; set; }
        [XmlIgnore]
        public virtual  User User { get; set; }
        [XmlIgnore]
        public virtual  User User1 { get; set; }
        [XmlIgnore]
        private ICollection<RoleMenuMap> _RoleMenuMaps;
        [XmlIgnore]
        public virtual ICollection<RoleMenuMap> RoleMenuMaps
        {
            get { return this._RoleMenuMaps ?? (this._RoleMenuMaps = new HashSet<RoleMenuMap>()); }
            set { this._RoleMenuMaps = value; }
        }
        [XmlIgnore]
        private ICollection<RolePermissionMap> _RolePermissionMaps;
        [XmlIgnore]
        public virtual ICollection<RolePermissionMap> RolePermissionMaps
        {
            get { return this._RolePermissionMaps ?? (this._RolePermissionMaps = new HashSet<RolePermissionMap>()); }
            set { this._RolePermissionMaps = value; }
        }
        [XmlIgnore]
        private ICollection<UserRoleMap> _UserRoleMaps;
        [XmlIgnore]
        public virtual ICollection<UserRoleMap> UserRoleMaps
        {
            get { return this._UserRoleMaps ?? (this._UserRoleMaps = new HashSet<UserRoleMap>()); }
            set { this._UserRoleMaps = value; }
        }
    }
}
