//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wicresoft.WFH.Data
{
    using System;
    using System.Data.Linq.Mapping;
    using System.Xml.Serialization;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [Serializable]
    [DataContract]
    [XmlRoot("RolePermissionMap")]
    public partial class RolePermissionMap : IdentityEntity
    {
    
        [Column(Name = "Id", DbType = "Int32", IsPrimaryKey = true, CanBeNull = false, IsDbGenerated = true)]
        public override int Id { get; set; }
    
        [Column(Name = "RoleId", DbType = "Int32", CanBeNull = false)]
        public  int RoleId { get; set; }
    
        [Column(Name = "PermissionId", DbType = "Int32", CanBeNull = false)]
        public  int PermissionId { get; set; }
        [XmlIgnore]
        public virtual  Permission Permission { get; set; }
        [XmlIgnore]
        public virtual  Role Role { get; set; }
    }
}
