//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wicresoft.WFH.Data
{
    using System;
    using System.Data.Linq.Mapping;
    using System.Xml.Serialization;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [Serializable]
    [DataContract]
    [XmlRoot("User")]
    public partial class User : BaseEntity
    {
        public User()
        {
        }
    
    
        [Column(Name = "Id", DbType = "Int32", IsPrimaryKey = true, CanBeNull = false, IsDbGenerated = true)]
        public override int Id { get; set; }
    
        [Column(Name = "OrganizationId", DbType = "Int32")]
        public  Nullable<int> OrganizationId { get; set; }
    
        [Column(Name = "ManagerId", DbType = "Int32")]
        public  Nullable<int> ManagerId { get; set; }
    
        [Column(Name = "Alias", DbType = "String", CanBeNull = false)]
        public  string Alias { get; set; }
    
        [Column(Name = "Name", DbType = "String", CanBeNull = false)]
        public  string Name { get; set; }
    
        [Column(Name = "Email", DbType = "String", CanBeNull = false)]
        public  string Email { get; set; }
    
        [Column(Name = "Password", DbType = "String", CanBeNull = false)]
        public  string Password { get; set; }
    
        [Column(Name = "IsEnable", DbType = "Boolean", CanBeNull = false)]
        public  bool IsEnable { get; set; }
    
        [Column(Name = "CreatedUserId", DbType = "Int32")]
        public  Nullable<int> CreatedUserId { get; set; }
    
        [Column(Name = "CreatedDateTime", DbType = "DateTime", CanBeNull = false)]
    	private System.DateTime _createdDateTime;
    	public virtual System.DateTime CreatedDateTime 
    	{
    		get { return _createdDateTime; }
    		set 
    		{
    			if (value.Kind == DateTimeKind.Unspecified) {
    				_createdDateTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_createdDateTime = value;
    			}
    		}
    	}
    
        [Column(Name = "LastUpdatedUserId", DbType = "Int32")]
        public  Nullable<int> LastUpdatedUserId { get; set; }
    
        [Column(Name = "LastUpdateDateTime", DbType = "DateTime", CanBeNull = false)]
    	private System.DateTime _lastUpdateDateTime;
    	public virtual System.DateTime LastUpdateDateTime 
    	{
    		get { return _lastUpdateDateTime; }
    		set 
    		{
    			if (value.Kind == DateTimeKind.Unspecified) {
    				_lastUpdateDateTime = DateTime.SpecifyKind(value, DateTimeKind.Utc);
    			} else {
    				_lastUpdateDateTime = value;
    			}
    		}
    	}
    
        [Column(Name = "IsActive", DbType = "Boolean", CanBeNull = false)]
        public override bool IsActive { get; set; }
        [XmlIgnore]
        private ICollection<AccessEvent> _AccessEvents;
        [XmlIgnore]
        public virtual ICollection<AccessEvent> AccessEvents
        {
            get { return this._AccessEvents ?? (this._AccessEvents = new HashSet<AccessEvent>()); }
            set { this._AccessEvents = value; }
        }
        [XmlIgnore]
        private ICollection<Organization> _Organizations;
        [XmlIgnore]
        public virtual ICollection<Organization> Organizations
        {
            get { return this._Organizations ?? (this._Organizations = new HashSet<Organization>()); }
            set { this._Organizations = value; }
        }
        [XmlIgnore]
        private ICollection<Organization> _Organizations1;
        [XmlIgnore]
        public virtual ICollection<Organization> Organizations1
        {
            get { return this._Organizations1 ?? (this._Organizations1 = new HashSet<Organization>()); }
            set { this._Organizations1 = value; }
        }
        [XmlIgnore]
        public virtual  Organization Organization { get; set; }
        [XmlIgnore]
        private ICollection<Role> _Roles;
        [XmlIgnore]
        public virtual ICollection<Role> Roles
        {
            get { return this._Roles ?? (this._Roles = new HashSet<Role>()); }
            set { this._Roles = value; }
        }
        [XmlIgnore]
        private ICollection<Role> _Roles1;
        [XmlIgnore]
        public virtual ICollection<Role> Roles1
        {
            get { return this._Roles1 ?? (this._Roles1 = new HashSet<Role>()); }
            set { this._Roles1 = value; }
        }
        [XmlIgnore]
        private ICollection<User> _User1;
        [XmlIgnore]
        public virtual ICollection<User> User1
        {
            get { return this._User1 ?? (this._User1 = new HashSet<User>()); }
            set { this._User1 = value; }
        }
        [XmlIgnore]
        public virtual  User CreatedUser { get; set; }
        [XmlIgnore]
        private ICollection<User> _User11;
        [XmlIgnore]
        public virtual ICollection<User> User11
        {
            get { return this._User11 ?? (this._User11 = new HashSet<User>()); }
            set { this._User11 = value; }
        }
        [XmlIgnore]
        public virtual  User UpdatedUser { get; set; }
        [XmlIgnore]
        private ICollection<User> _User12;
        [XmlIgnore]
        public virtual ICollection<User> User12
        {
            get { return this._User12 ?? (this._User12 = new HashSet<User>()); }
            set { this._User12 = value; }
        }
        [XmlIgnore]
        public virtual  User User4 { get; set; }
        [XmlIgnore]
        private ICollection<UserPermissionMap> _UserPermissionMaps;
        [XmlIgnore]
        public virtual ICollection<UserPermissionMap> UserPermissionMaps
        {
            get { return this._UserPermissionMaps ?? (this._UserPermissionMaps = new HashSet<UserPermissionMap>()); }
            set { this._UserPermissionMaps = value; }
        }
        [XmlIgnore]
        private ICollection<UserRoleMap> _UserRoleMaps;
        [XmlIgnore]
        public virtual ICollection<UserRoleMap> UserRoleMaps
        {
            get { return this._UserRoleMaps ?? (this._UserRoleMaps = new HashSet<UserRoleMap>()); }
            set { this._UserRoleMaps = value; }
        }
        [XmlIgnore]
        private ICollection<Device> _Devices;
        [XmlIgnore]
        public virtual ICollection<Device> Devices
        {
            get { return this._Devices ?? (this._Devices = new HashSet<Device>()); }
            set { this._Devices = value; }
        }
        [XmlIgnore]
        private ICollection<Device> _Devices1;
        [XmlIgnore]
        public virtual ICollection<Device> Devices1
        {
            get { return this._Devices1 ?? (this._Devices1 = new HashSet<Device>()); }
            set { this._Devices1 = value; }
        }
    }
}
